optimizer: Adam 
lr: 0.0001
wd: 0.0001
epoch: 10
batch_size: 32
seed: 1234
lr_decay: keras
amsgrad: 1   #for adam optim
mg: 1


#model-related
model:
  margin: 2
  nb_samp: 64000
  first_conv: 128   # no. of filter coefficients 
  in_channels: 1
  win_size: 100
  enc_in: 100
  c_out: 512
  n_heads: 8
  d_model: 512
  d_ff: 512
  e_layers: 3
  filts: [128, [128, 128], [128, 512], [512, 512]]
  nb_fc_node: 1024
  gru_node: 1024
  nb_gru_layer: 3
  nb_classes: 2
  
  



